source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!

post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
  end
end

target 'WProgressHUD_Example' do
  pod 'WProgressHUD', :path => '../WProgressHUD.podspec'
end